// Copy từ labasset-api/src/notifications/notification-types.ts (registry backend).
// Nhãn hiển thị lấy theo registry; khi backend thêm loại mới, chạy lại bước copy trong WEB-NOTES.
export const NOTIFICATION_TYPES: Record<string, string> = {
  'repair.new': 'Phiếu sửa chữa mới',
  'repair.assigned': 'Được phân công sửa chữa',
  'repair.assignment_declined': 'Từ chối nhận sửa chữa',
  'repair.completed': 'Hoàn thành sửa chữa',
  'repair.acceptance_rejected': 'Từ chối nghiệm thu',
  'repair.overdue': 'Sửa chữa quá hạn',
  'repair.cost_warning': 'Chi phí sửa chữa vượt ngưỡng',
  'request.pending': 'Phiếu yêu cầu chờ duyệt',
  'request.pending_dept': 'Phiếu yêu cầu chờ trưởng khoa',
  'request.approved': 'Phiếu yêu cầu đã duyệt',
  'request.partially_approved': 'Phiếu yêu cầu duyệt một phần',
  'request.rejected': 'Phiếu yêu cầu bị từ chối',
  'request.shortage': 'Thiếu tồn khi giữ hàng',
  'request.issued': 'Đã cấp phát đủ',
  'request.partially_issued': 'Cấp phát một phần',
  'request.received': 'Khoa đã nhận hàng',
  'request.receive_reminder': 'Nhắc nhận hàng',
  'request.comment': 'Bình luận phiếu yêu cầu',
  'request.recurring_created': 'Phiếu định kỳ đã tạo',
  'equipment.transfer.pending': 'Chờ duyệt điều chuyển',
  'equipment.transfer.approved': 'Đã duyệt điều chuyển',
  'equipment.transfer.rejected': 'Từ chối điều chuyển',
  'equipment.transfer.cancelled': 'Huỷ điều chuyển',
  'equipment.component.warning': 'Linh kiện sắp đến hạn',
  'equipment.component.due': 'Linh kiện đến hạn thay',
  'stocktake.assigned': 'Được phân công kiểm kê',
  'stocktake.closed': 'Đợt kiểm kê đã chốt',
  'maintenance.overdue': 'Bảo dưỡng quá hạn',
  'maintenance.due': 'Sắp đến hạn bảo dưỡng',
  'maintenance.done': 'Hoàn thành bảo dưỡng',
  'maintenance.skipped': 'Bỏ qua bảo dưỡng',
  'maintenance.rescheduled': 'Dời lịch bảo dưỡng',
  'calibration.overdue': 'Kiểm định quá hạn',
  'calibration.due': 'Sắp đến hạn kiểm định',
  'calibration.rescheduled': 'Dời lịch kiểm định',
  'calibration.failed': 'Kiểm định không đạt',
  'calibration.conditional': 'Kiểm định đạt có điều kiện',
  'stock.alerts.daily': 'Cảnh báo tồn kho trong ngày',
  'fault.suggestion.accepted': 'Đề xuất lỗi được chấp nhận',
  'fault.suggestion.rejected': 'Đề xuất lỗi bị từ chối',
}

export const NOTIFICATION_TYPE_KEYS = Object.keys(NOTIFICATION_TYPES)
